name: Java CI with Maven

on:
  push:
    branches: [ "main", "dev", "release" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.14'
    - name: Check Out Dependencies
      run: git clone --branch v7.4 --depth 1 https://github.com/conveyal/r5.git
    - name: Build Dependencies
      run: cd r5 && gradle publishToMavenLocal
    - name: Maven Build
      run: mvn -B package --file pom.xml
